FROM ros:humble

# Install Python deps and CycloneDDS RMW
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
    ros-humble-rmw-cyclonedds-cpp \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ros_ws

COPY ros_ws/src ./src

# Build the workspace
RUN bash -c "\
    source /opt/ros/humble/setup.bash && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release \
"

SHELL ["/bin/bash", "-c"]
